# cp settings.yaml /root/.config/Ultralytics/settings.yaml
settings_version: 0.0.4
datasets_dir: /usr/src/ultralytics/home/data
weights_dir: /usr/src/ultralytics/weights
runs_dir: /usr/src/ultralytics/home/home/gis/Project/112_yolov8/runs
uuid: 8765e340dc3a16f2d81ba2b190673429a59e3c2aa9083be50ddaa72612f8b714
sync: true
api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
